import "./globals.css";
import Navbar from "@/components/navbar.js";

export const metadata = {
  title: "New Next.js App",
  description: "Generated by Copilot",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
